# Generated by Django 5.2.1 on 2025-05-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_set_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='set_password',
        ),
    ]
