# Generated by Django 5.2.1 on 2025-05-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_user_set_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_password',
            field=models.BooleanField(default=False),
        ),
    ]
