# Generated by Django 5.2.1 on 2025-05-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_check_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='check_password',
            new_name='is_password_checked',
        ),
    ]
